# Generated by Django 4.0.1 on 2022-01-29 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_post_background_image_post_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('avatar', models.ImageField(upload_to='profile_image/')),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=70)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
