# Generated by Django 4.0.1 on 2022-01-29 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Userprofile',
        ),
    ]
